const productFullDetails = [
  {
    slug: "MicroBT_WhatsMiner_M60_(172Th)", // match backend slug
    productName: "MicroBT WhatsMiner M60 (172Th)",

    overview: `
The MicroBT WhatsMiner M60 (172 Th/s) is a next-generation SHA-256 ASIC miner built for Bitcoin and Bitcoin Cash mining.

It features 172 Th/s (±5%) hashrate with only 3,422 W (±5%) power usage, offering exceptional efficiency of 19.895 J/TH — making it one of the most efficient miners of 2024.

With 5nm chip technology, stable performance, and industrial-grade cooling, the M60 is ideal for serious miners seeking long-term profitability.
    `,

    specifications: [
      { label: "Manufacturer", value: "MicroBT" },
      { label: "Model", value: "WhatsMiner M60 (172 Th/s)" },
      { label: "Algorithm", value: "SHA-256" },
      { label: "Hashrate", value: "172 TH/s (±5%)" },
      { label: "Power Consumption", value: "3,422 W (±5%)" },
      { label: "Energy Efficiency", value: "19.895 J/TH" },
      { label: "Chip Size", value: "5 nm" },
      { label: "Cooling System", value: "Dual-fan air cooling" },
      { label: "Noise Level", value: "75 dB" },
      { label: "Network Connection", value: "Ethernet" },
      { label: "Power Supply", value: "Integrated PSU" },
      { label: "Input Voltage", value: "200-240V AC" },
      { label: "Dimensions", value: "430 × 155 × 226 mm" },
      { label: "Weight", value: "13.5 kg" },
      { label: "Operating Temperature", value: "–5°C to 35°C" },
      { label: "Release Date", value: "February 2024" },
    ],
  },
  {
    slug: "ElphaPex_DG1+_(14Gh)",
    overview: `The ElphaPex DG1+ (14 Gh/s) is a high-performance ASIC miner designed for the Scrypt algorithm, optimized for mining Litecoin (LTC) and Dogecoin (DOGE) simultaneously. Delivering a hashrate of 14 Gh/s (±3%) at a power draw of 3,920 W (±10%), it achieves a power efficiency of 0.28 J/Mh, making it one of the most efficient miners in its category.
Built for reliability, the DG1+ features a sturdy industrial design with four high-speed fans that ensure stable cooling and consistent operation. Operating at around 75 dB, it’s best suited for professional mining setups and industrial environments.
With its proven Scrypt mining architecture, strong build quality, and high hashrate performance, the ElphaPex DG1+ (14 Gh/s) is an excellent choice for miners looking to maximize long-term profitability and stability while mining both LTC and DOGE.`,
    specifications: [
      { label: "Manufacturer", value: "ElphaPex" },
      { label: "Model", value: "DG1+ (14 Gh/s)" },
      { label: "Algorithm", value: "Scrypt" },
      { label: "Hashrate", value: "14 Gh/s (±3%)" },
      { label: "Power Consumption", value: "3,920 W (±10%)" },
      { label: "Energy Efficiency", value: "0.28 J/Mh" },
      { label: "Generation", value: "5th Generation – 2021" },
      { label: "Cooling System", value: "Air-cooled with 4 fans" },
      { label: "Noise Level", value: "75 dB" },
      { label: "Network Connection", value: "RJ45 Ethernet 10/100 M" },
      { label: "Power Supply", value: "Integrated PSU" },
      { label: "Input Voltage", value: "200 – 240 V AC" },
      { label: "Dimensions", value: "432 × 196 × 287 mm" },
      { label: "Weight", value: "18.3 kg" },
      { label: "Operating Temperature", value: "5 °C – 45 °C" },
      { label: "Humidity Range", value: "5 % – 95 % RH" },
      { label: "Release Date", value: "July 2024" },
    ],
  },

  {
    slug: "Jingle_Miner_BTC_Solo_Lite_(1.2TH)",
    overview: `The Jingle Miner BTC Solo Lite (1.2TH/s) is a compact, ultra-efficient SHA-256d ASIC miner designed by JingleMining for solo or small-scale Bitcoin mining. It achieves a hashrate of 1.2 TH/s (±5%) while consuming only 23 W (±5%), delivering an exceptional energy efficiency of 19.17 J/TH making it one of the most power-efficient Bitcoin miners in its class.
Powered by the BM1370 ASIC chip, originally developed for the Antminer S21 Pro, the BTC Solo Lite brings industrial-level performance to a small plug-and-play device ideal for desktop mining setups.`,
    specifications: [
      { label: "Manufacturer", value: "JingleMining" },
      { label: "Model", value: "BTC Solo Lite (1.2 TH/s)" },
      { label: "Algorithm", value: "SHA-256d" },
      { label: "Hashrate", value: "1.2 TH/s (±5%)" },
      { label: "Power Consumption", value: "23 W (±5%)" },
      { label: "Energy Efficiency", value: "19.17 J/TH" },
      { label: "Input Voltage", value: "5 V DC" },
      { label: "Cooling System", value: "Silent air-cooling" },
      { label: "Noise Level", value: "Low-noise operation" },
      { label: "Dimensions (Net)", value: "114.4 × 66 × 58 mm" },
      { label: "Dimensions (Gross)", value: "170 × 152 × 92 mm" },
      { label: "Weight (Net)", value: "0.25 kg" },
      { label: "Weight (Gross)", value: "0.65 kg" },
      { label: "Accessory", value: "PSU (5V/5A) with adapters" },
      { label: "Release Date", value: "2024" },
    ],
  },

  {
    slug: "goldshell-xt-box-sha3x-580ghs",
    overview: `The Goldshell XT-BOX (580 Gh/s) is a compact and efficient ASIC miner for the SHA3x algorithm, purpose-built to mine Tari (XTM). It delivers a hashrate of 580 Gh/s (±5%) while consuming only 400 W (±5%), with an energy efficiency of 0.69 J/Gh.`,
    specifications: [
      { label: "Manufacturer", value: "Goldshell" },
      { label: "Model", value: "XT-BOX (580 Gh/s)" },
      { label: "Algorithm", value: "SHA3x" },
      { label: "Hashrate", value: "580 Gh/s (±5%)" },
      { label: "Power Consumption", value: "400 W (±5%)" },
      { label: "Energy Efficiency", value: "0.69 J/Gh" },
      { label: "Cooling System", value: "Dual-fan air cooling" },
      { label: "Noise Level", value: "35 dB" },
      { label: "Network Connection", value: "Ethernet / Wi-Fi" },
      { label: "Power Supply", value: "Integrated PSU" },
      { label: "Input Voltage", value: "110 – 240 V AC" },
      { label: "Dimensions", value: "198 × 150 × 95 mm" },
      { label: "Weight", value: "2.43 kg" },
      { label: "Operating Temperature", value: "5 °C – 35 °C" },
      { label: "Release Date", value: "September 2025" },
    ],
  },

  {
    slug: "Canaan_Avalon_Q_(90Th)",
    overview: `The Canaan Avalon Q (90 Th/s) is a highly efficient SHA-256 ASIC miner built with 4 nm chip technology, providing 90 Th/s at 1,674 W for outstanding power efficiency and quiet operation (45 dB).`,
    specifications: [
      { label: "Manufacturer", value: "Canaan" },
      { label: "Model", value: "Avalon Q (90 Th/s)" },
      { label: "Algorithm", value: "SHA-256" },
      { label: "Hashrate", value: "90 Th/s (±5%)" },
      { label: "Power Consumption", value: "1,674 W (±5%)" },
      { label: "Energy Efficiency", value: "0.019 J/Gh" },
      { label: "Generation", value: "7th Generation – 2023" },
      { label: "Chip Size", value: "4 nm" },
      { label: "Chip Count", value: "160" },
      { label: "Cooling System", value: "Air-cooled with 2 fans" },
      { label: "Noise Level", value: "45 dB" },
      { label: "Network Connection", value: "Ethernet / Wi-Fi" },
      { label: "Power Supply", value: "Integrated PSU" },
      { label: "Input Voltage", value: "110 – 240 V AC" },
      { label: "Dimensions", value: "455 × 130 × 440 mm" },
      { label: "Weight", value: "10.5 kg" },
      { label: "Operating Temperature", value: "0 °C – 35 °C" },
      { label: "Release Date", value: "April 2025" },
    ],
  },

  {
    slug: "Bitmain_Antminer_L9_(17Gh)",
    overview: `The Bitmain Antminer L9 (17 Gh/s) is a next-generation Scrypt miner designed for dual mining Litecoin (LTC) and Dogecoin (DOGE), delivering 17 Gh/s with a power consumption of 3,570 W and excellent energy efficiency.`,
    specifications: [
      { label: "Manufacturer", value: "Bitmain" },
      { label: "Model", value: "Antminer L9 (17 Gh/s)" },
      { label: "Algorithm", value: "Scrypt" },
      { label: "Hashrate", value: "17 Gh/s (±5%)" },
      { label: "Power Consumption", value: "3,570 W (±5%)" },
      { label: "Energy Efficiency", value: "0.21 J/Mh" },
      { label: "Cooling System", value: "Air-cooled with 2 fans" },
      { label: "Noise Level", value: "75 dB" },
      { label: "Input Voltage", value: "200 – 240 V AC" },
      { label: "Dimensions", value: "195 × 290 × 379 mm" },
      { label: "Weight", value: "13.5 kg" },
      { label: "Operating Temperature", value: "5 °C – 45 °C" },
      { label: "Release Date", value: "May 2024" },
    ],
  },
  {
    slug: "IceRiver_KAS_KS7_(30Th)",
    name: "IceRiver KAS KS7 (30 Th/s)",
    overview: `The IceRiver KAS KS7 (30 Th/s) is a powerful ASIC miner engineered for the kHeavyHash algorithm, purpose-built to mine Kaspa (KAS) and compatible coins. Delivering an exceptional hashrate of 30 Th/s (±5%) at a power consumption of 3,500 W (±5%), it achieves an outstanding energy efficiency of 0.117 J/Gh.

Designed for professional mining environments, the KS7 features robust air cooling with four high-speed fans and reliable components for stable 24/7 operation. With low noise levels and durable build, the KS7 stands out as one of the most dependable and profitable Kaspa miners in 2025.`,
    specifications: [
      { label: "Manufacturer", value: "IceRiver" },
      { label: "Model", value: "KAS KS7 (30 Th/s)" },
      { label: "Algorithm", value: "kHeavyHash" },
      { label: "Hashrate", value: "30 Th/s (±5%)" },
      { label: "Power Consumption", value: "3,500 W (±5%)" },
      { label: "Energy Efficiency", value: "0.117 J/Gh" },
      { label: "Generation", value: "5th Generation – 2025" },
      { label: "Cooling System", value: "Air-cooled with 4 fans" },
      { label: "Noise Level", value: "75 dB" },
      { label: "Network Connection", value: "Ethernet" },
      { label: "Power Supply", value: "Integrated PSU" },
      { label: "Input Voltage", value: "200 - 250 V AC" },
      { label: "Dimensions", value: "430 × 195 × 290 mm" },
      { label: "Weight", value: "17.5 kg" },
      { label: "Operating Temperature", value: "5 °C – 40 °C" },
      { label: "Humidity Range", value: "10 % – 90 % RH" },
      { label: "Release Date", value: "April 2025" },
    ],
  },
  {
    slug: "Bitmain_Antminer_KS7_(40Th)",
    name: "Bitmain Antminer KS7 (40 Th/s)",
    overview: `The Bitmain Antminer KS7 (40 Th/s) is a high-performance ASIC miner built for the kHeavyHash algorithm, optimized for Kaspa (KAS). Delivering 40 Th/s (±5%) at 3,080 W, it achieves 0.077 J/Gh efficiency — making it one of the most power-efficient Kaspa miners available.

With Bitmain’s advanced ASIC technology, four-fan cooling system, and stable 24/7 operation, the KS7 stands among the most profitable Kaspa mining rigs in 2025.`,
    specifications: [
      { label: "Manufacturer", value: "Bitmain" },
      { label: "Model", value: "Antminer KS7 (40 Th/s)" },
      { label: "Algorithm", value: "kHeavyHash" },
      { label: "Hashrate", value: "40 Th/s (±5%)" },
      { label: "Power Consumption", value: "3,080 W (±5%)" },
      { label: "Energy Efficiency", value: "0.077 J/Gh" },
      { label: "Generation", value: "6th Generation – 2025" },
      { label: "Cooling System", value: "Air-cooled with 4 fans" },
      { label: "Noise Level", value: "75 dB" },
      { label: "Network Connection", value: "Ethernet" },
      { label: "Power Supply", value: "Integrated PSU" },
      { label: "Input Voltage", value: "220 – 277 V AC" },
      { label: "Dimensions", value: "430 × 196 × 290 mm" },
      { label: "Weight", value: "16.4 kg" },
      { label: "Operating Temperature", value: "5 °C – 45 °C" },
      { label: "Humidity Range", value: "10 % – 90 % RH" },
      { label: "Release Date", value: "May 2025" },
    ],
  },
  {
    slug: "Bitmain_Antminer_KS5_(20Th)",
    name: "Bitmain Antminer KS5 (20 Th/s)",
    overview: `The Bitmain Antminer KS5 (20 Th/s) is optimized for the kHeavyHash algorithm and Kaspa mining. With 20 Th/s hashrate and 3,000 W power draw, it offers 0.15 J/Gh efficiency, making it an excellent mid-range Kaspa miner.

Built with Bitmain’s advanced ASIC design, dual-fan cooling, and reliable hardware, the KS5 is a strong entry-level / scaling option for Kaspa miners.`,
    specifications: [
      { label: "Manufacturer", value: "Bitmain" },
      { label: "Model", value: "Antminer KS5 (20 Th/s)" },
      { label: "Algorithm", value: "kHeavyHash" },
      { label: "Hashrate", value: "20 Th/s (±5%)" },
      { label: "Power Consumption", value: "3,000 W (±5%)" },
      { label: "Energy Efficiency", value: "0.15 J/Gh" },
      { label: "Generation", value: "4th Generation – 2024" },
      { label: "Cooling System", value: "Air-cooled with 2 fans" },
      { label: "Noise Level", value: "75 dB" },
      { label: "Network Connection", value: "Ethernet" },
      { label: "Power Supply", value: "Integrated PSU" },
      { label: "Input Voltage", value: "200 – 240 V AC" },
      { label: "Dimensions", value: "195 × 290 × 430 mm" },
      { label: "Weight", value: "16.1 kg" },
      { label: "Operating Temperature", value: "5 °C – 45 °C" },
      { label: "Humidity Range", value: "5 % – 95 % RH" },
      { label: "Release Date", value: "March 2024" },
    ],
  },
  {
    slug: "Bitmain_Antminer_S19k_Pro_(120Th)",
    name: "Bitmain Antminer S19K Pro (120 Th/s)",
    overview: `The Bitmain Antminer S19k Pro (120 Th/s) is a proven SHA-256 Bitcoin miner delivering 120 Th/s at 2,760 W with 23 J/Th efficiency. Designed for industrial crypto mining farms, it offers reliable uptime, powerful cooling, and competitive efficiency — a strong choice for Bitcoin miners in 2025.`,
    specifications: [
      { label: "Manufacturer", value: "Bitmain" },
      { label: "Model", value: "Antminer S19k Pro (120 Th/s)" },
      { label: "Algorithm", value: "SHA-256" },
      { label: "Hashrate", value: "120 Th/s (±5%)" },
      { label: "Power Consumption", value: "2,760 W (±5%)" },
      { label: "Energy Efficiency", value: "23 J/Th" },
      { label: "Generation", value: "6th Generation – 2020" },
      { label: "Cooling System", value: "Air-cooled with 4 fans" },
      { label: "Noise Level", value: "75 dB" },
      { label: "Network Connection", value: "Ethernet" },
      { label: "Input Voltage", value: "12 V" },
      { label: "Dimensions", value: "195 × 290 × 370 mm" },
      { label: "Weight", value: "13.2 kg" },
      { label: "Operating Temperature", value: "5 °C – 45 °C" },
      { label: "Humidity Range", value: "5 % – 95 % RH" },
      { label: "Release Date", value: "April 2023" },
    ],
  },
  {
    slug: "Bitmain_Antminer_S21_XP_Hyd_(473Th) ",
    name: "Bitmain Antminer S21 XP Hyd (473 Th/s)",
    overview: `The Bitmain Antminer S21 XP Hyd (473 Th/s) is a cutting-edge hydro-cooled Bitcoin miner offering industry-leading efficiency of 12 J/Th. With water cooling, extremely low noise (50 dB), and 473 Th/s performance, it is one of the most advanced Bitcoin mining machines of 2025.`,
    specifications: [
      { label: "Manufacturer", value: "Bitmain" },
      { label: "Model", value: "Antminer S21 XP Hyd (473 Th/s)" },
      { label: "Algorithm", value: "SHA-256" },
      { label: "Hashrate", value: "473 Th/s (±5%)" },
      { label: "Power Consumption", value: "5,676 W (±5%)" },
      { label: "Energy Efficiency", value: "12 J/Th" },
      { label: "Cooling System", value: "Hydro-cooling" },
      { label: "Noise Level", value: "50 dB" },
      { label: "Network Connection", value: "Ethernet" },
      { label: "Input Voltage", value: "200 – 240 V AC" },
      { label: "Dimensions", value: "410 × 170 × 209 mm" },
      { label: "Weight", value: "17.5 kg (approx.)" },
      { label: "Operating Temperature", value: "5 °C – 45 °C" },
      { label: "Humidity Range", value: "5 % – 95 % RH" },
      { label: "Release Date", value: "November 2024" },
    ],
  },
  {
    slug: "Bitmain_Antminer_S21+_(235Th)",
    name: "Bitmain Antminer S21+ (235 Th/s)",
    overview: `The Bitmain Antminer S21+ (235 Th/s) is an ultra-efficient SHA-256 miner achieving 235 Th/s at 3,877 W, delivering 16.498 J/Th efficiency. Designed for maximum profitability and durability, it is ideal for industrial Bitcoin mining setups in 2025.`,
    specifications: [
      { label: "Manufacturer", value: "Bitmain" },
      { label: "Model", value: "Antminer S21+ (235 Th/s)" },
      { label: "Algorithm", value: "SHA-256" },
      { label: "Hashrate", value: "235 Th/s (±5%)" },
      { label: "Power Consumption", value: "3,877 W (±5%)" },
      { label: "Energy Efficiency", value: "16.498 J/Th" },
      { label: "Cooling System", value: "Air-cooled with 2 fans" },
      { label: "Noise Level", value: "75 dB" },
      { label: "Network Connection", value: "Ethernet" },
      { label: "Input Voltage", value: "200 – 240 V AC" },
      { label: "Dimensions", value: "400 × 195 × 290 mm" },
      { label: "Weight", value: "15.5 kg (approx.)" },
      { label: "Operating Temperature", value: "10 °C – 40 °C" },
      { label: "Humidity Range", value: "10 % – 90 % RH" },
      { label: "Release Date", value: "June 2025" },
    ],
  },
  {
    slug: "Bitmain_Antminer_S21_Pro_(234Th)",
    productName: "Bitmain Antminer S21 Pro (234 Th/s)",
    overview: `The Bitmain Antminer S21 Pro (234 Th/s) is an advanced SHA-256 ASIC miner engineered for high-efficiency Bitcoin (BTC) and Bitcoin Cash (BCH) mining. With a maximum hashrate of 234 Th/s (±5%) and a power consumption of 3,510 W (±5%), it achieves an outstanding energy efficiency of 15 J/Th, setting a new benchmark for air-cooled mining machines.

Powered by Bitmain’s enhanced ASIC chip design, the S21 Pro delivers stable performance and optimized power efficiency for long-term mining operations. Its dual-fan cooling system ensures superior airflow and thermal balance, while the sturdy build supports consistent uptime even in demanding environments.

The Antminer S21 Pro (234 Th/s) is a top-tier solution for industrial and professional miners seeking maximum profitability, long-lasting durability, and cutting-edge performance in 2025.`,

    specifications: [
      { label: "Manufacturer", value: "Bitmain" },
      { label: "Model", value: "Antminer S21 Pro (234 Th/s)" },
      { label: "Algorithm", value: "SHA-256" },
      { label: "Hashrate", value: "234 Th/s (±5%)" },
      { label: "Power Consumption", value: "3,510 W (±5%)" },
      { label: "Energy Efficiency", value: "15 J/Th" },
      { label: "Generation", value: "7th Generation - 2023" },
      { label: "Cooling System", value: "Air-cooled with 2 fans" },
      { label: "Noise Level", value: "75 dB" },
      { label: "Network Connection", value: "Ethernet" },
      { label: "Power Supply", value: "Integrated PSU" },
      { label: "Input Voltage", value: "200 – 240 V AC" },
      { label: "Dimensions", value: "400 × 195 × 290 mm" },
      { label: "Weight", value: "15.5 kg (approx.)" },
      { label: "Operating Temperature", value: "5 °C – 45 °C" },
      { label: "Humidity Range", value: "5 % – 95 % RH" },
      { label: "Release Date", value: "July 2024" },
    ],
  },
  {
    slug: "Bitmain_Antminer_L7_(9.5Gh)",
    productName: "Bitmain Antminer L7 (9.5 Gh/s)",
    overview: `The Bitmain Antminer L7 (9.5 Gh/s) is a high-efficiency Scrypt ASIC miner designed for mining Litecoin (LTC) and Dogecoin (DOGE) simultaneously. Delivering a hashrate of 9.5 Gh/s (±5%) while consuming 3,425 W (±5%), it achieves impressive energy efficiency at 0.361 J/Mh. With stable performance, advanced cooling, and reliable chip architecture, the L7 remains a top choice for profitable LTC + DOGE mining in 2025.`,

    specifications: [
      { label: "Manufacturer", value: "Bitmain" },
      { label: "Model", value: "Antminer L7 (9.5Gh/s)" },
      { label: "Algorithm", value: "Scrypt" },
      { label: "Hashrate", value: "9.5Gh/s (±5%)" },
      { label: "Power Consumption", value: "3,425 W (±5%)" },
      { label: "Energy Efficiency", value: "0.361 J/Mh" },
      { label: "Generation", value: "5th Generation – 2021" },
      { label: "Cooling System", value: "Air-cooled with 4 fans" },
      { label: "Noise Level", value: "75 dB" },
      { label: "Network Connection", value: "Ethernet" },
      { label: "Power Supply", value: "Integrated PSU" },
      { label: "Input Voltage", value: "200 – 240 V AC" },
      { label: "Dimensions", value: "195 × 290 × 370 mm" },
      { label: "Weight", value: "15 kg" },
      { label: "Operating Temperature", value: "5 °C - 45 °C" },
      { label: "Humidity Range", value: "5 % - 95 % RH" },
      { label: "Release Date", value: "November 2021" },
    ],
  },
  {
    slug: "Bitmain_Antminer_L9_(16Gh)",
    productName: "Bitmain Antminer L9 (16 Gh/s)",
    overview: `The Bitmain Antminer L9 (16Gh/s) is a high-performance Scrypt ASIC miner for Litecoin (LTC) and Dogecoin (DOGE). With a 16Gh/s hashrate and 3,360W power draw, it offers excellent energy efficiency of 0.21 J/Mh. Engineered for powerful and stable mining, it stands as one of the most efficient LTC + DOGE miners in 2025.`,

    specifications: [
      { label: "Manufacturer", value: "Bitmain" },
      { label: "Model", value: "Antminer L9 (16Gh/s)" },
      { label: "Algorithm", value: "Scrypt" },
      { label: "Hashrate", value: "16Gh/s (±5%)" },
      { label: "Power Consumption", value: "3,360 W (±5%)" },
      { label: "Energy Efficiency", value: "0.21 J/Mh" },
      { label: "Generation", value: "7th Generation - 2024" },
      { label: "Cooling System", value: "Air-cooled with 2 fans" },
      { label: "Noise Level", value: "75 dB" },
      { label: "Network Connection", value: "Ethernet" },
      { label: "Power Supply", value: "Integrated PSU" },
      { label: "Input Voltage", value: "200 – 240 V AC" },
      { label: "Dimensions", value: "195 × 290 × 379 mm" },
      { label: "Weight", value: "13.5 kg" },
      { label: "Operating Temperature", value: "5 °C - 45 °C" },
      { label: "Humidity Range", value: "5 % - 95 % RH" },
      { label: "Release Date", value: "May 2024" },
    ],
  },
  {
    slug: "Bitmain_Antminer_KS5_Pro_(21Th)",
    productName: "Bitmain Antminer KS5 Pro (21 Th/s)",
    overview: `The Bitmain Antminer KS5 Pro (21Th/s) is a next-generation KHeavyHash ASIC miner optimized for Kaspa (KAS). Delivering 21Th/s with only 3,150W power draw, it offers top-tier 0.15 J/Gh efficiency. Built for reliability, efficiency, and continuous 24/7 mining.`,

    specifications: [
      { label: "Manufacturer", value: "Bitmain" },
      { label: "Model", value: "Antminer KS5 Pro (21Th/s)" },
      { label: "Algorithm", value: "KHeavyHash" },
      { label: "Hashrate", value: "21Th/s (±5%)" },
      { label: "Power Consumption", value: "3,150 W (±5%)" },
      { label: "Energy Efficiency", value: "0.15 J/Gh" },
      { label: "Generation", value: "4th Generation – 2024" },
      { label: "Cooling System", value: "Air-cooled with 2 fans" },
      { label: "Noise Level", value: "75 dB" },
      { label: "Network Connection", value: "Ethernet" },
      { label: "Power Supply", value: "Integrated PSU" },
      { label: "Input Voltage", value: "200 – 240 V AC" },
      { label: "Dimensions", value: "195 × 290 × 430 mm" },
      { label: "Weight", value: "16.1 kg" },
      { label: "Operating Temperature", value: "5 °C - 45 °C" },
      { label: "Humidity Range", value: "5 % - 95 % RH" },
      { label: "Release Date", value: "March 2024" },
    ],
  },
  {
    slug: "bitmain-antminer-al1-pro-16-6th",
    productName: "Bitmain Antminer AL1 Pro (16.6 Th/s)",
    overview: `The Bitmain Antminer AL1 Pro (16.6Th/s) is a high-efficiency Blake3 ASIC miner for Alephium (ALPH). It offers 16.6Th/s at 3,730W for an excellent 0.225 J/Gh efficiency, with advanced cooling and 24/7 stable performance.`,

    specifications: [
      { label: "Manufacturer", value: "Bitmain" },
      { label: "Model", value: "Antminer AL1 Pro (16.6Th/s)" },
      { label: "Algorithm", value: "Blake3" },
      { label: "Hashrate", value: "16.6 Th/s (±5%)" },
      { label: "Power Consumption", value: "3,730 W (±5%)" },
      { label: "Energy Efficiency", value: "0.225 J/Gh" },
      { label: "Generation", value: "2nd Generation - 2024" },
      { label: "Cooling System", value: "Air-cooled with 4 fans" },
      { label: "Noise Level", value: "75 dB" },
      { label: "Network Connection", value: "Ethernet" },
      { label: "Power Supply", value: "Integrated PSU" },
      { label: "Input Voltage", value: "220 – 270 V AC" },
      { label: "Dimensions", value: "195 × 290 × 400 mm" },
      { label: "Weight", value: "13.6 kg" },
      { label: "Operating Temperature", value: "5 °C - 45 °C" },
      { label: "Humidity Range", value: "5 % - 95 % RH" },
      { label: "Release Date", value: "September 2024" },
    ],
  },
];

export default productFullDetails;
